apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_IMAGE_NAME}-configmap
  labels:
    app: ${APP_IMAGE_NAME}
data:
  API_SERVER_ALERT_URL: ""
  API_SERVER_ALERT_PORT: ""
  API_NAME_ALERT_POST: ""
  API_SERVER_METRIC_URL: ""
  API_SERVER_METRIC_PORT: ""
  API_NAME_METRIC_POST: ""
  API_SERVER_METRIC_RECEIVED_URL: ""
  API_SERVER_METRIC_RECEIVED_PORT: ""
  API_NAME_METRIC_RECEIVED_POST: ""
  API_SERVER_RESOURCE_URL: "http://nexclipper-api.nc.svc.cluster.local"
  API_SERVER_RESOURCE_PORT: "5001"
  API_NAME_RESOURCE_POST: "/resourceMass"
  MQCOMMM_PORT: "4001"
  NODE_EXPORTER_PORT: "9090"
  RABBITMQ_SERVER_PORT: "5672"
  RABBITMQ_SERVER_QUEUE_ALERT: "nc_alert"
  RABBITMQ_SERVER_QUEUE_METRIC: "nc_metric"
  RABBITMQ_SERVER_QUEUE_METRIC_RECEIVED: "nc_metric_received"
  RABBITMQ_SERVER_QUEUE_RESOURCE: "nc_resource"
  RABBITMQ_SERVER_QUEUE_VIRTUAL_HOST: "nexclipper"
  RABBITMQ_SERVER_URL: "ncmq-rabbitmq.rabbitmq.svc.cluster.local"
  RABBITMQ_SERVER_USER: "nexclipper"
  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_IMAGE_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_IMAGE_NAME}
  template:
    metadata:
      labels:
        app: ${APP_IMAGE_NAME}
    spec:
      containers:
      - name: ${APP_IMAGE_NAME}
        image: ${IMG_TAG_TO_DEPLOY}
        envFrom:
          - configMapRef:
              name: ${APP_IMAGE_NAME}-configmap
        env:
          - name: RABBITMQ_SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ncmq-rabbitmq
                key: rabbitmq-password
        ports:
        - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_IMAGE_NAME}
spec:
  selector:
    app: ${APP_IMAGE_NAME}
  ports:
  - port: 4001
    targetPort: 4001
