apiVersion: v1
kind: Namespace
metadata:
  name:  nc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_IMAGE_NAME}-configmap
  labels:
    app: ${APP_IMAGE_NAME} 
data:
  API_SERVER_ALERT_URL: "http://nexclipper-connect.nc.svc.cluster.local"
  API_SERVER_ALERT_PORT: "8081"
  API_NAME_ALERT_POST: "/service/alert_rule"
  API_SERVER_METRIC_URL: "http://nexclipper-connect.nc.svc.cluster.local"
  API_SERVER_METRIC_PORT: "8081"
  API_NAME_METRIC_POST: "/service/metric_meta"
  API_SERVER_METRIC_RECEIVED_URL: "http://nexclipper-api.nc.svc.cluster.local"
  API_SERVER_METRIC_RECEIVED_PORT: "5001"
  API_NAME_METRIC_RECEIVED_POST: "/metricReceivedMassVm"
  API_SERVER_RESOURCE_URL: "http://nexclipper-api.nc.svc.cluster.local"
  API_SERVER_RESOURCE_PORT: "5001"
  API_NAME_RESOURCE_POST: "/resourceMass"
  API_SERVER_RESOURCE_EVENT_URL: "http://nexclipper-api.nc.svc.cluster.local"
  API_SERVER_RESOURCE_EVENT_PORT: "5001"
  API_NAME_RESOURCE_EVENT_POST: "/resourceEventMass"
  MQCOMM_PORT: "4001"
  NODE_EXPORTER_PORT: "9100"
  RABBITMQ_SERVER_PORT: "5672"
  RABBITMQ_SERVER_QUEUE_ALERT: "co_alert"
  RABBITMQ_SERVER_QUEUE_METRIC: "co_metric"
  RABBITMQ_SERVER_QUEUE_METRIC_RECEIVED: "co_metric_received"
  RABBITMQ_SERVER_QUEUE_RESOURCE: "co_resource"
  RABBITMQ_SERVER_QUEUE_RESOURCE_OPS: "ops_resource"
  RABBITMQ_SERVER_QUEUE_METRIC_OPS: "ops_metric"
  RABBITMQ_SERVER_VIRTUAL_HOST: "claion"
  RABBITMQ_SERVER_URL: "ncmq-rabbitmq.rabbitmq.svc.cluster.local"
  RABBITMQ_SERVER_USER: "claion"
  RABBITMQ_SERVER_PASSWORD: "claion"
  MQCOMM_RESOURCE_TARGET_DB: "MARIADB"
  MAX_API_BODY_SIZE: 500mb
  NODE_OPTIONS: "--max-old-space-size=8192"
  VM_URL: "http://vm-victoria-metrics-single-server.vm.svc.cluster.local:8428/api/v1/import?extra_label=clusterUuid="
  VM_MULTI_AUTH_URL: "http://vm-auth-victoria-metrics-auth.vm-multi-tenant.svc.cluster.local:8427/api/v1/import?extra_label=clusterUuid="
  API_NAME_CUSTOMER_ACCOUNT_GET: "/customerAccount/resourceGroup"
  VM_OPTION: "SINGLE"

  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_IMAGE_NAME}
spec:
  revisionHistoryLimit: 0 # Default to 10 if not specified
  selector:
    matchLabels:
      app: ${APP_IMAGE_NAME}
  template:
    metadata:
      labels:
        app: ${APP_IMAGE_NAME}
    spec:
      containers:
      - name: ${APP_IMAGE_NAME}
        image: ${IMG_TAG_TO_DEPLOY}
        imagePullPolicy: Always
        resources: {}
        envFrom:
          - configMapRef:
              name: ${APP_IMAGE_NAME}-configmap
        env:
          - name: RABBITMQ_SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ncmq-rabbitmq
                key: rabbitmq-password
        ports:
        - containerPort: 4001
        livenessProbe:
          httpGet:
            path: /health
            port: 4001
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_IMAGE_NAME}
spec:
  selector:
    app: ${APP_IMAGE_NAME}
  ports:
  - port: 4001
    targetPort: 4001
